"""
This file was autogenerated by pybind11-stubs, and then modified manually to fix
some errors.
"""
from __future__ import annotations
from numoop._numoop import DataFrame
from numoop._numoop import load
from . import _numoop
__all__: list[str] = ['__doc__', '__version__', 'DataFrame', 'load']
__version__: str = 'dev'
